name: 'snowplow_web_integration_tests'
version: '0.3.0'
config-version: 2

profile: 'integration_tests'

source-paths: ["models"]
analysis-paths: ["analysis"] 
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"

quoting:
  identifier: false
  schema: false
  
models:
  snowplow_web_integration_tests:
    bind: false
    +schema: "snowplow_int_tests"
    source:
      bigquery:
        +enabled: "{{ target.type == 'bigquery' | as_bool() }}"
      redshift:
        +enabled: "{{ target.type == 'redshift' | as_bool() }}"
      snowflake:
        +enabled: "{{ target.type == 'snowflake' | as_bool() }}"



vars:
  snowplow__enable_custom_example: false
  snowplow_web:
    snowplow__events: "{{ ref('snowplow_web_events_stg') }}"
    snowplow__page_view_context: "{{ ref('snowplow_web_page_view_context_stg') }}"
    snowplow__start_date: "2021-03-01"
    snowplow__backfill_limit_days: 2


seeds:
  quote_columns: false
  snowplow_web_integration_tests:
    +schema: "snowplow_int_tests"
    source:
      snowplow_web_events:
        +column_types:
          app_id: "{{ 'varchar' if target.type == 'redshift' else 'string' }}" 
          etl_tstamp: timestamp
          collector_tstamp: timestamp
          dvce_created_tstamp: timestamp
          user_fingerprint: "{{ 'varchar' if target.type == 'redshift' else 'string' }}" 
          ip_isp: "{{ 'varchar' if target.type == 'redshift' else 'string' }}" 
          ip_organization: "{{ 'varchar' if target.type == 'redshift' else 'string' }}" 
          ip_domain: "{{ 'varchar' if target.type == 'redshift' else 'string' }}" 
          ip_netspeed: "{{ 'varchar' if target.type == 'redshift' else 'string' }}" 
          page_urlfragment: "{{ 'varchar' if target.type == 'redshift' else 'string' }}" 
          refr_urlfragment: "{{ 'varchar' if target.type == 'redshift' else 'string' }}" 
          refr_medium: "{{ 'varchar' if target.type == 'redshift' else 'string' }}" 
          refr_source: "{{ 'varchar' if target.type == 'redshift' else 'string' }}" 
          refr_term: "{{ 'varchar' if target.type == 'redshift' else 'string' }}" 
          mkt_term: "{{ 'varchar' if target.type == 'redshift' else 'string' }}" 
          mkt_content: "{{ 'varchar' if target.type == 'redshift' else 'string' }}" 
          se_label: "{{ 'varchar' if target.type == 'redshift' else 'string' }}" 
          se_property: "{{ 'varchar' if target.type == 'redshift' else 'string' }}" 
          se_value: float
          tr_orderid: "{{ 'varchar' if target.type == 'redshift' else 'string' }}" 
          tr_affiliation: "{{ 'varchar' if target.type == 'redshift' else 'string' }}" 
          tr_total: float
          tr_tax: float
          tr_shipping: float
          tr_city: "{{ 'varchar' if target.type == 'redshift' else 'string' }}" 
          tr_state: "{{ 'varchar' if target.type == 'redshift' else 'string' }}" 
          tr_country: "{{ 'varchar' if target.type == 'redshift' else 'string' }}" 
          ti_orderid: "{{ 'varchar' if target.type == 'redshift' else 'string' }}" 
          ti_sku: "{{ 'varchar' if target.type == 'redshift' else 'string' }}" 
          ti_name: "{{ 'varchar' if target.type == 'redshift' else 'string' }}" 
          ti_category: "{{ 'varchar' if target.type == 'redshift' else 'string' }}" 
          ti_price: float
          br_name: "{{ 'varchar' if target.type == 'redshift' else 'string' }}" 
          br_family: "{{ 'varchar' if target.type == 'redshift' else 'string' }}" 
          br_version: "{{ 'varchar' if target.type == 'redshift' else 'string' }}" 
          br_type: "{{ 'varchar' if target.type == 'redshift' else 'string' }}" 
          br_renderengine: "{{ 'varchar' if target.type == 'redshift' else 'string' }}" 
          br_colordepth: "{{ 'varchar' if target.type == 'redshift' else 'string' }}" 
          os_name: "{{ 'varchar' if target.type == 'redshift' else 'string' }}" 
          os_family: "{{ 'varchar' if target.type == 'redshift' else 'string' }}" 
          os_manufacturer: "{{ 'varchar' if target.type == 'redshift' else 'string' }}" 
          dvce_type: "{{ 'varchar' if target.type == 'redshift' else 'string' }}" 
          dvce_ismobile: boolean
          tr_currency: "{{ 'varchar' if target.type == 'redshift' else 'string' }}" 
          tr_total_base: float
          tr_tax_base: float
          tr_shipping_base: float
          ti_currency: "{{ 'varchar' if target.type == 'redshift' else 'string' }}" 
          ti_price_base: float
          base_currency: "{{ 'varchar' if target.type == 'redshift' else 'string' }}" 
          etl_tags: "{{ 'varchar' if target.type == 'redshift' else 'string' }}" 
          dvce_sent_tstamp: timestamp
          refr_domain_userid: "{{ 'varchar' if target.type == 'redshift' else 'string' }}" 
          refr_dvce_tstamp: timestamp
          derived_tstamp: timestamp
          true_tstamp: timestamp


    expected:
      bigquery:
        +enabled: "{{ target.type == 'bigquery' | as_bool() }}"
        snowplow_web_page_views_expected:
          +column_types:
            horizontal_percentage_scrolled: float
            vertical_percentage_scrolled: float
            dvce_created_tstamp: timestamp
            collector_tstamp: timestamp
            derived_tstamp: timestamp
            start_tstamp: timestamp
            end_tstamp: timestamp
            page_urlfragment: string
            mkt_term: string
            mkt_content: string
            refr_urlfragment: string
            refr_medium: string
            refr_source: string
            refr_term: string
            br_colordepth: string
            br_renderengine: string
            category: string
            primary_impact: string
            reason: string
            spider_or_robot: boolean
            useragent_family: string
            useragent_major: string
            useragent_minor: string
            useragent_patch: string
            useragent_version: string
            os_family: string
            os_major: string
            os_minor: string
            os_patch: string
            os_patch_minor: string
            os_version: string
            device_family: string
            device_class: string
            agent_class: string
            agent_name: string
            agent_name_version: string
            agent_name_version_major: string
            agent_version: string
            agent_version_major: string
            device_brand: string
            device_name: string
            device_version: string
            layout_engine_class: string
            layout_engine_name: string
            layout_engine_name_version: string
            layout_engine_name_version_major: string
            layout_engine_version: string
            layout_engine_version_major: string
            operating_system_class: string
            operating_system_name: string
            operating_system_name_version: string
            operating_system_version: string
        snowplow_web_sessions_expected:
          +column_types:
            app_id: string
            start_tstamp: timestamp
            end_tstamp: timestamp
            first_page_urlfragment: string
            last_page_urlfragment: string
            refr_urlquery: string
            refr_urlfragment: string
            refr_medium: string
            refr_source: string
            refr_term: string
            mkt_term: string
            mkt_content: string
            br_renderengine: string
            category: string
            primary_impact: string
            reason: string
            spider_or_robot: boolean
            useragent_family: string
            useragent_major: string
            useragent_minor: string
            useragent_patch: string
            useragent_version: string
            os_family: string
            os_major: string
            os_minor: string
            os_patch: string
            os_patch_minor: string
            os_version: string
            device_family: string
            device_class: string
            agent_class: string
            agent_name: string
            agent_name_version: string
            agent_name_version_major: string
            agent_version: string
            agent_version_major: string
            device_brand: string
            device_name: string
            device_version: string
            layout_engine_class: string
            layout_engine_name: string
            layout_engine_name_version: string
            layout_engine_name_version_major: string
            layout_engine_version: string
            layout_engine_version_major: string
            operating_system_class: string
            operating_system_name: string
            operating_system_name_version: string
            operating_system_version: string
        snowplow_web_users_expected:
          +column_types:
            start_tstamp: timestamp
            end_tstamp: timestamp
            first_page_urlfragment: string
            last_page_urlfragment: string
            refr_urlquery: string
            refr_urlfragment: string
            refr_medium: string
            refr_source: string
            refr_term: string
            mkt_term: string
            mkt_content: string
      redshift:
        +enabled: "{{ target.type == 'redshift' | as_bool() }}"
        snowplow_web_page_views_expected:
          +column_types:
            app_id: varchar
            horizontal_percentage_scrolled: float
            vertical_percentage_scrolled: float
            dvce_created_tstamp: timestamp
            collector_tstamp: timestamp
            derived_tstamp: timestamp
            start_tstamp: timestamp
            end_tstamp: timestamp
            page_urlfragment: varchar
            mkt_term: varchar
            mkt_content: varchar
            refr_urlfragment: varchar
            refr_medium: varchar
            refr_source: varchar
            refr_term: varchar
            br_colordepth: varchar
            br_renderengine: varchar
            category: varchar
            primary_impact: varchar
            reason: varchar
            spider_or_robot: boolean
            useragent_family: varchar
            useragent_major: varchar
            useragent_minor: varchar
            useragent_patch: varchar
            useragent_version: varchar
            os_family: varchar
            os_major: varchar
            os_minor: varchar
            os_patch: varchar
            os_patch_minor: varchar
            os_version: varchar
            device_family: varchar
            device_class: varchar
            agent_class: varchar
            agent_name: varchar
            agent_name_version: varchar
            agent_name_version_major: varchar
            agent_version: varchar
            agent_version_major: varchar
            device_brand: varchar
            device_name: varchar
            device_version: varchar
            layout_engine_class: varchar
            layout_engine_name: varchar
            layout_engine_name_version: varchar
            layout_engine_name_version_major: varchar
            layout_engine_version: varchar
            layout_engine_version_major: varchar
            operating_system_class: varchar
            operating_system_name: varchar
            operating_system_name_version: varchar
            operating_system_version: varchar
        snowplow_web_sessions_expected:
          +column_types:
            app_id: varchar
            start_tstamp: timestamp
            end_tstamp: timestamp
            first_page_urlfragment: varchar
            last_page_urlfragment: varchar
            refr_urlquery: varchar
            refr_urlfragment: varchar
            refr_medium: varchar
            refr_source: varchar
            refr_term: varchar
            mkt_term: varchar
            mkt_content: varchar
            last_page_urlquery: varchar
            br_renderengine: varchar
            category: varchar
            primary_impact: varchar
            reason: varchar
            spider_or_robot: boolean
            useragent_family: varchar
            useragent_major: varchar
            useragent_minor: varchar
            useragent_patch: varchar
            useragent_version: varchar
            os_family: varchar
            os_major: varchar
            os_minor: varchar
            os_patch: varchar
            os_patch_minor: varchar
            os_version: varchar
            device_family: varchar
            device_class: varchar
            agent_class: varchar
            agent_name: varchar
            agent_name_version: varchar
            agent_name_version_major: varchar
            agent_version: varchar
            agent_version_major: varchar
            device_brand: varchar
            device_name: varchar
            device_version: varchar
            layout_engine_class: varchar
            layout_engine_name: varchar
            layout_engine_name_version: varchar
            layout_engine_name_version_major: varchar
            layout_engine_version: varchar
            layout_engine_version_major: varchar
            operating_system_class: varchar
            operating_system_name: varchar
            operating_system_name_version: varchar
            operating_system_version: varchar
        snowplow_web_users_expected:
          +column_types:
            start_tstamp: timestamp
            end_tstamp: timestamp
            first_page_urlfragment: varchar
            last_page_urlfragment: varchar
            last_page_urlquery: varchar
            refr_urlquery: varchar
            refr_urlfragment: varchar
            refr_medium: varchar
            refr_source: varchar
            refr_term: varchar
            mkt_term: varchar
            mkt_content: varchar
      snowflake:
        +enabled: "{{ target.type == 'snowflake' | as_bool() }}"
        snowplow_web_page_views_expected:
          +column_types:
            app_id: varchar
            horizontal_percentage_scrolled: float
            vertical_percentage_scrolled: float
            dvce_created_tstamp: timestamp
            collector_tstamp: timestamp
            derived_tstamp: timestamp
            start_tstamp: timestamp
            end_tstamp: timestamp
            page_urlfragment: varchar
            mkt_term: varchar
            mkt_content: varchar
            refr_urlfragment: varchar
            refr_medium: varchar
            refr_source: varchar
            refr_term: varchar
            br_colordepth: varchar
            br_renderengine: varchar
            category: varchar
            primary_impact: varchar
            reason: varchar
            spider_or_robot: boolean
            useragent_family: varchar
            useragent_major: varchar
            useragent_minor: varchar
            useragent_patch: varchar
            useragent_version: varchar
            os_family: varchar
            os_major: varchar
            os_minor: varchar
            os_patch: varchar
            os_patch_minor: varchar
            os_version: varchar
            device_family: varchar
            device_class: varchar
            agent_class: varchar
            agent_name: varchar
            agent_name_version: varchar
            agent_name_version_major: varchar
            agent_version: varchar
            agent_version_major: varchar
            device_brand: varchar
            device_name: varchar
            device_version: varchar
            layout_engine_class: varchar
            layout_engine_name: varchar
            layout_engine_name_version: varchar
            layout_engine_name_version_major: varchar
            layout_engine_version: varchar
            layout_engine_version_major: varchar
            operating_system_class: varchar
            operating_system_name: varchar
            operating_system_name_version: varchar
            operating_system_version: varchar
        snowplow_web_sessions_expected:
          +column_types:
            app_id: varchar
            start_tstamp: timestamp
            end_tstamp: timestamp
            first_page_urlfragment: varchar
            last_page_urlfragment: varchar
            refr_urlquery: varchar
            refr_urlfragment: varchar
            refr_medium: varchar
            refr_source: varchar
            refr_term: varchar
            mkt_term: varchar
            mkt_content: varchar
            last_page_urlquery: varchar
            br_renderengine: varchar
            category: varchar
            primary_impact: varchar
            reason: varchar
            spider_or_robot: boolean
            useragent_family: varchar
            useragent_major: varchar
            useragent_minor: varchar
            useragent_patch: varchar
            useragent_version: varchar
            os_family: varchar
            os_major: varchar
            os_minor: varchar
            os_patch: varchar
            os_patch_minor: varchar
            os_version: varchar
            device_family: varchar
            device_class: varchar
            agent_class: varchar
            agent_name: varchar
            agent_name_version: varchar
            agent_name_version_major: varchar
            agent_version: varchar
            agent_version_major: varchar
            device_brand: varchar
            device_name: varchar
            device_version: varchar
            layout_engine_class: varchar
            layout_engine_name: varchar
            layout_engine_name_version: varchar
            layout_engine_name_version_major: varchar
            layout_engine_version: varchar
            layout_engine_version_major: varchar
            operating_system_class: varchar
            operating_system_name: varchar
            operating_system_name_version: varchar
            operating_system_version: varchar
        snowplow_web_users_expected:
          +column_types:
            start_tstamp: timestamp
            end_tstamp: timestamp
            first_page_urlfragment: varchar
            last_page_urlfragment: varchar
            last_page_urlquery: varchar
            refr_urlquery: varchar
            refr_urlfragment: varchar
            refr_medium: varchar
            refr_source: varchar
            refr_term: varchar
            mkt_term: varchar
            mkt_content: varchar

